spring:
  application:
    name: blood-sample-management-system-api
  datasource:
    username: root
    password: saisuhas@421
    url: jdbc:mysql://localhost:3306/bsm_e_db?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  properties:
    hibernate:
      format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: saisuhaskampli421@gmail.com
    password: wgjlcujjqsmgmwnj
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
